[project]
name = "renovate-python-optionals"
version = "0.0.0"

[project.optional-dependencies]
test = [
    "pytest ~= 8.3.0",
]
docs = [
    "sphinx == 8.2.2",
    "furo ==2025.7.19",
]

[dependency-groups]
dev = [
    "pre-commit == 4.2.0",
    "mypy == 1.17.0",
]
